import { Acl, RestApi } from '@servicenow/sdk/core'
import {
    createCollectionQuiz,
    getCurrentUserRoles,
    getCollectionsList,
    getOpenCollectionOverview,
    getQuizDetail,
    publishCollection,
    removeCollectionForCurrentUser,
    saveCollectionForCurrentUser,
    saveQuizProgress,
    submitQuiz,
} from '../../server/rest-api/quiz-simulator-api'

const quizSimulatorApiAcl = Acl({
    $id: Now.ID['quiz_simulator_api_execute'],
    name: 'quiz_simulator_api',
    type: 'rest_endpoint',
    operation: 'execute',
    roles: ['x_2119443_quiz_sim.user'],
    securityAttribute: 'user_is_authenticated',
    adminOverrides: false,
})

const quizSimulatorApiAuthenticatedAcl = Acl({
    $id: Now.ID['quiz_simulator_api_authenticated_execute'],
    name: 'quiz_simulator_api_authenticated',
    type: 'rest_endpoint',
    operation: 'execute',
    securityAttribute: 'user_is_authenticated',
    adminOverrides: false,
})

RestApi({
    $id: Now.ID['quiz_simulator_api'],
    name: 'Quiz Simulator API',
    serviceId: 'quiz_simulator_api',
    shortDescription: 'Application REST API for Quiz Simulator',
    consumes: 'application/json',
    produces: 'application/json',
    routes: [
        {
            $id: Now.ID['quiz_simulator_api_me_roles'],
            name: 'Current user roles',
            method: 'GET',
            path: '/me/roles',
            script: getCurrentUserRoles,
            authentication: true,
            authorization: true,
            produces: 'application/json',
            enforceAcl: [quizSimulatorApiAuthenticatedAcl],
            consumes: 'application/json',
        },
        {
            $id: Now.ID['quiz_simulator_api_collections_list'],
            name: 'Collections list',
            method: 'GET',
            path: '/collections',
            script: getCollectionsList,
            parameters: [
                {
                    $id: Now.ID['quiz_simulator_api_collections_list_saved_only_param'],
                    name: 'saved_only',
                    required: false,
                    exampleValue: 'true',
                    shortDescription: 'If true, returns only collections saved by the authenticated user',
                },
            ],
            authentication: true,
            authorization: true,
            produces: 'application/json',
            enforceAcl: [quizSimulatorApiAcl],
            consumes: 'application/json',
        },
        {
            $id: Now.ID['quiz_simulator_api_collections_save'],
            name: 'Save collection',
            method: 'POST',
            path: '/collections/save',
            script: saveCollectionForCurrentUser,
            authentication: true,
            authorization: true,
            consumes: 'application/json',
            produces: 'application/json',
            enforceAcl: [quizSimulatorApiAcl],
        },
        {
            $id: Now.ID['quiz_simulator_api_collections_remove'],
            name: 'Remove saved collection',
            method: 'POST',
            path: '/collections/remove',
            script: removeCollectionForCurrentUser,
            consumes: 'application/json',
            produces: 'application/json',
            authentication: true,
            authorization: true,
            enforceAcl: [quizSimulatorApiAcl],
        },
        {
            $id: Now.ID['quiz_simulator_api_collections_publish'],
            name: 'Publish collection with questions and answers',
            method: 'POST',
            path: '/collections/publish',
            script: publishCollection,
            consumes: 'application/json',
            produces: 'application/json',
            authentication: true,
            authorization: true,
            enforceAcl: [quizSimulatorApiAcl],
        },
        {
            $id: Now.ID['quiz_simulator_api_collections_open_overview'],
            name: 'Open collection overview',
            method: 'GET',
            path: '/collections/open-overview',
            script: getOpenCollectionOverview,
            parameters: [
                {
                    $id: Now.ID['quiz_simulator_api_collections_open_overview_collection_id_param'],
                    name: 'collection_id',
                    required: true,
                    exampleValue: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                    shortDescription: 'Saved collection sys_id',
                },
            ],
            authentication: true,
            authorization: true,
            produces: 'application/json',
            enforceAcl: [quizSimulatorApiAcl],
            consumes: 'application/json',
        },
        {
            $id: Now.ID['quiz_simulator_api_quizzes_create'],
            name: 'Create quiz from collection',
            method: 'POST',
            path: '/quizzes/create',
            script: createCollectionQuiz,
            authentication: true,
            authorization: true,
            consumes: 'application/json',
            produces: 'application/json',
            enforceAcl: [quizSimulatorApiAcl],
        },
        {
            $id: Now.ID['quiz_simulator_api_quizzes_detail'],
            name: 'Get quiz detail',
            method: 'GET',
            path: '/quizzes/detail',
            script: getQuizDetail,
            parameters: [
                {
                    $id: Now.ID['quiz_simulator_api_quizzes_detail_quiz_id_param'],
                    name: 'quiz_id',
                    required: true,
                    exampleValue: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                    shortDescription: 'Quiz sys_id',
                },
            ],
            authentication: true,
            authorization: true,
            produces: 'application/json',
            enforceAcl: [quizSimulatorApiAcl],
            consumes: 'application/json',
        },
        {
            $id: Now.ID['quiz_simulator_api_quizzes_save_progress'],
            name: 'Save quiz progress',
            method: 'POST',
            path: '/quizzes/save-progress',
            script: saveQuizProgress,
            authentication: true,
            authorization: true,
            consumes: 'application/json',
            produces: 'application/json',
            enforceAcl: [quizSimulatorApiAcl],
        },
        {
            $id: Now.ID['quiz_simulator_api_quizzes_submit'],
            name: 'Submit quiz answers',
            method: 'POST',
            path: '/quizzes/submit',
            script: submitQuiz,
            authentication: true,
            authorization: true,
            consumes: 'application/json',
            produces: 'application/json',
            enforceAcl: [quizSimulatorApiAcl],
        },
    ],
})
