import { Acl, RestApi } from '@servicenow/sdk/core'
import {
    createCollectionTest,
    getCurrentUserRoles,
    getCollectionsList,
    getOpenCollectionOverview,
    getTestDetail,
    publishCollection,
    removeCollectionForCurrentUser,
    saveCollectionForCurrentUser,
    saveTestProgress,
    submitTest,
} from '../../server/rest-api/test-simulator-api'

const testSimulatorApiAcl = Acl({
    $id: Now.ID['test_simulator_api_execute'],
    name: 'test_simulator_api',
    type: 'rest_endpoint',
    operation: 'execute',
    roles: ['x_2119443_test_sim.user', 'x_2119443_test_sim.admin'],
    securityAttribute: 'user_is_authenticated',
    adminOverrides: false,
})

const testSimulatorApiAuthenticatedAcl = Acl({
    $id: Now.ID['test_simulator_api_authenticated_execute'],
    name: 'test_simulator_api_authenticated',
    type: 'rest_endpoint',
    operation: 'execute',
    securityAttribute: 'user_is_authenticated',
    adminOverrides: false,
})

RestApi({
    $id: Now.ID['test_simulator_api'],
    name: 'Test Simulator API',
    serviceId: 'test_simulator_api',
    shortDescription: 'Application REST API for Test Simulator',
    consumes: 'application/json',
    produces: 'application/json',
    routes: [
        {
            $id: Now.ID['test_simulator_api_me_roles'],
            name: 'Current user roles',
            method: 'GET',
            path: '/me/roles',
            script: getCurrentUserRoles,
            authentication: true,
            authorization: true,
            produces: 'application/json',
            enforceAcl: [testSimulatorApiAuthenticatedAcl],
        },
        {
            $id: Now.ID['test_simulator_api_collections_list'],
            name: 'Collections list',
            method: 'GET',
            path: '/collections',
            script: getCollectionsList,
            parameters: [
                {
                    $id: Now.ID['test_simulator_api_collections_list_saved_only_param'],
                    name: 'saved_only',
                    required: false,
                    exampleValue: 'true',
                    shortDescription: 'If true, returns only collections saved by the authenticated user',
                },
            ],
            authentication: true,
            authorization: true,
            produces: 'application/json',
            enforceAcl: [testSimulatorApiAcl],
        },
        {
            $id: Now.ID['test_simulator_api_collections_save'],
            name: 'Save collection',
            method: 'POST',
            path: '/collections/save',
            script: saveCollectionForCurrentUser,
            authentication: true,
            authorization: true,
            consumes: 'application/json',
            produces: 'application/json',
            enforceAcl: [testSimulatorApiAcl],
        },
        {
            $id: Now.ID['test_simulator_api_collections_remove'],
            name: 'Remove saved collection',
            method: 'POST',
            path: '/collections/remove',
            script: removeCollectionForCurrentUser,
            consumes: 'application/json',
            produces: 'application/json',
            authentication: true,
            authorization: true,
            enforceAcl: [testSimulatorApiAcl],
        },
        {
            $id: Now.ID['test_simulator_api_collections_publish'],
            name: 'Publish collection with questions and answers',
            method: 'POST',
            path: '/collections/publish',
            script: publishCollection,
            consumes: 'application/json',
            produces: 'application/json',
            authentication: true,
            authorization: true,
            enforceAcl: [testSimulatorApiAcl],
        },
        {
            $id: Now.ID['test_simulator_api_collections_open_overview'],
            name: 'Open collection overview',
            method: 'GET',
            path: '/collections/open-overview',
            script: getOpenCollectionOverview,
            parameters: [
                {
                    $id: Now.ID['test_simulator_api_collections_open_overview_collection_id_param'],
                    name: 'collection_id',
                    required: true,
                    exampleValue: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                    shortDescription: 'Saved collection sys_id',
                },
            ],
            authentication: true,
            authorization: true,
            produces: 'application/json',
            enforceAcl: [testSimulatorApiAcl],
        },
        {
            $id: Now.ID['test_simulator_api_tests_create'],
            name: 'Create test from collection',
            method: 'POST',
            path: '/tests/create',
            script: createCollectionTest,
            authentication: true,
            authorization: true,
            consumes: 'application/json',
            produces: 'application/json',
            enforceAcl: [testSimulatorApiAcl],
        },
        {
            $id: Now.ID['test_simulator_api_tests_detail'],
            name: 'Get test detail',
            method: 'GET',
            path: '/tests/detail',
            script: getTestDetail,
            parameters: [
                {
                    $id: Now.ID['test_simulator_api_tests_detail_test_id_param'],
                    name: 'test_id',
                    required: true,
                    exampleValue: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                    shortDescription: 'Test sys_id',
                },
            ],
            authentication: true,
            authorization: true,
            produces: 'application/json',
            enforceAcl: [testSimulatorApiAcl],
        },
        {
            $id: Now.ID['test_simulator_api_tests_save_progress'],
            name: 'Save test progress',
            method: 'POST',
            path: '/tests/save-progress',
            script: saveTestProgress,
            authentication: true,
            authorization: true,
            consumes: 'application/json',
            produces: 'application/json',
            enforceAcl: [testSimulatorApiAcl],
        },
        {
            $id: Now.ID['test_simulator_api_tests_submit'],
            name: 'Submit test answers',
            method: 'POST',
            path: '/tests/submit',
            script: submitTest,
            authentication: true,
            authorization: true,
            consumes: 'application/json',
            produces: 'application/json',
            enforceAcl: [testSimulatorApiAcl],
        },
    ],
})